### ISSUE TITLE
New function exposing that hides the mutable parser?

### ISSUE THREAD

**Issue by droundy** [simon-whitehead/rust-yard#8]
The current API is not hard to use, but it seems like it'd be cleaner if you exported a function

```
pub fn calculate(s: &str) -> Result<f64,String> {
  let mut parser = ShuntingYard::new();
  parser.calculate(s)
}
```

Note that I'd also prefer a `String` error over a vec of strings.  But the question of optimal error types is a thorny one, and it's not hard to convert between error types.

**Comment by simon-whitehead** [comment]
Hi @droundy ,

Honestly I wasn't aware people were using this library at all. Your two opened issues are good suggestions, but if I am honest I would probably re-write this library completely now that I'm 2 years into my Rust journey.

I'll see where I'm at in the next few weeks to begin re-writing it. I'm a little busy at the moment but hopefully I can at least make a start (and include your two suggestions).

Thanks!

**Comment by droundy** [comment]
Actually, after I opened this issue, I found a different library that serves my needs better.

**Comment by simon-whitehead** [comment]
Perfect - I'm glad your immediate needs are sorted. Apologies for the low quality code in this library. It was very much a "learn Rust" project.

**Comment by droundy** [comment]
I don't think it is low quality, just a bit less polished.  You can produce
good things while learning! My [arrayref](https://crates.io/crates/arrayref)
crate was also something of a learning project, but turned out to be useful
for a surprising number of people.
